version: '3'

services:
  frontend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/src

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.production
      args:
        - ENDPOINT=${ENDPOINT}
