name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Audit
        run: docker-compose run frontend npm audit
      - name: Lint
        run: docker-compose run frontend npm run lint
      - name: Jest
        run: docker-compose run frontend npm run jest
