name: My Simple Action

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: mrako/simple-action@master
        with:
          who-to-greet: Eficode
